# Workflow for Android CI

name: CI Android Debug Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # fs-extra dependency requires node v10+
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

    # # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:
    # - uses: actions/checkout@v1
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - name: Setup Gradle
    #   uses: gradle/gradle-build-action@v2
    # - name: Specify Gradle version
    #   run: ./gradlew wrapper --gradle-version-7.3.1
    # - name: CI dbg build
    #   run: |
    #     npm install
    #     npm install -g gulp
    #     npm install -g cordova
    #     npm link gulp
    #     gulp prep-android-dir
    #     gulp --debug
        
      # env:
      #   CI: true
